- name: Echoing in loops
  hosts: all
  gather_facts: false
  tasks:
    - name: Echo var
      ansible.builtin.command: /bin/echo "Hello World {{item}}"
      loop: [ "Ada", "Alexa" ]
      register: resp
    - name: Print result
      debug:
        var: resp
        