#SPDX-License-Identifier: MIT-0
---
# tasks file for printfile
- name: Display file contents
  ansible.builtin.command: "cat {{show_file}}"
  register: command_output
- name: Print to console
  ansible.builtin.debug:
    msg: "{{command_output.stdout}}"
