- name: Block example
  hosts: all
  become: true
  tasks:
    - name: Attempt to install a package
      block:
        - name: install an invalid package
          ansible.builtin.dnf:
            name: kjdkdjkjfd
      rescue:
        - ansible.builtin.debug:
            msg: "Oh! there is an error"
      always:
        - ansible.builtin.debug:
            msg: "This always executes"
