---
- name: Manage SELinux policy example 1
  hosts: all
  become: true
  vars:
    selinux_state: enforcing
    selinux_ports:
      - ports: "22100"
        proto: "tcp"
        setype: "ssh_port_t"
        state: "present"

  tasks:
    - name: Run SELinux role
      ansible.builtin.include_role:
        name: linux-system-roles.selinux
  post_tasks:
    - name: Reboot the systems
      ansible.builtin.reboot:
