Vagrant.configure("2") do |config|
  
  config.vm.define "staging" do |staging|
    # staging.vm.box = "fedora/37-cloud-base"
    staging.vm.box = "bento/almalinux-9"
    # staging.vm.box_version = "37.20221105.0"
    staging.vm.box_version = "202511.24.0"
    staging.ssh.password = "vagrant"
    staging.vm.network "public_network", use_dhcp_assigned_default_route: true
    staging.ssh.forward_agent = true
    staging.vm.provision "shell", inline: "ip -4 -o a"
  end
  
  config.vm.define "prod" do |prod|
    # staging.vm.box = "fedora/37-cloud-base"
    prod.vm.box = "bento/almalinux-9"
    # prod.vm.box_version = "37.20221105.0"
    prod.vm.box_version = "202511.24.0"
    prod.ssh.password = "vagrant"
    prod.vm.network "public_network", use_dhcp_assigned_default_route: true
    prod.ssh.forward_agent = true
    prod.vm.provision "shell", inline: "ip -4 -o a"
  end
  
  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/almalinux-9"
    node1.vm.box_version = "202511.24.0"
    # This sets the SSH connection to expect the new user credentials
    node1.ssh.username = "vagrant"
    node1.ssh.password = "vagrant"
  
    node1.vm.network "public_network", use_dhcp_assigned_default_route: true
    node1.ssh.forward_agent = true
  
    # Provisioning: Create user, set password, and add to sudoers
    node1.vm.provision "shell", inline: <<-SHELL
      useradd -m alex
      echo "alex:alex" | chpasswd
      usermod -aG wheel alex
    SHELL
  end
  
  config.vm.provider "vmware_desktop" do |vmw|
    vmw.memory = "2048"
  end
end
